export default {
  sendMessage: '/user/getCode', // 发送验证码
  register: '/user/managerRegister', // 园长注册
  login: '/user/managerLogin', // 园长登录
  getSchoolByAccountId: '/school/getSchoolByAccountId', // 通过Id得到学校
  editSchool: '/school/editData', // 修改学校信息
  getBroadcastPager: '/account/selectBroadcastPager', // 分页查询公告
  selectAdminPager: '/broadcast/selectAdminPager', // 得到多个园的公告
  getBroadcastById: '/broadcast/getDataById', // 通过Id得到公告
  deleteBroadcastById: '/broadcast/deleteData', // 删除公告
  addBroadcast: '/broadcast/addData', // 新增公告
  findClassesByLoginIdPager: '/account/findClassesByLoginIdPager', // 根据登录ID分页获取该用户下所有班级
  getTeacherPagerByLoginId: '/user/getTeacherPager', // 得到该园所有老师
  dismissClsases: '/account/dismissClasses', // 解散班级
  managerCreateClass: '/account/managerCreateClass', // 园长创建班级
  managerEditClass: '/account/managerEditClass', // 园长修改班级
  findClassesById: '/classes/findClassesById', // 通过id得到班级
  findNoSelectTeacherByClassesId: '/classes/findNoSelectTeacherByClassesId', // 根据班级id得到未选教师
  adminAddTeacherToClasses: '/classes/adminAddTeacherToClasses', // 园长新增挂靠老师
  adminRemoveClassesTeacher: '/classes/adminRemoveClassesTeacher', // 园长移除班级老师
  findClassesByTeacherId: '/classes/findClassesByTeacherId', // 根据teacherId得到所在班级
  findTeacherByClassesId: '/classes/findTeacherByClassesId', // 根据班级ID获取该班级的所有老师
  findStudentByClassesId: '/student/findStudentByClassesId', // 根据班级查询该班级的学生
  selectClassesByAccountId: '/account/selectClassesByAccountId', // 根据管理员id获取班级
  changeStudentClasses: '/account/changeStudentClasses', // 学生转班
  getDeptsByLoginId: '/department/getDeptsByLoginId', // 获取学校下的部门,
  getAllJob: '/job/getAllJob', // 得到所有职务,
  addTeacherToSchool: '/user/addTeacher', // 园长添加老师
  managerEditTeacher: '/user/editTeacher', // 园长编辑老师
  unbindingTeacher: '/user/unbinding', // 园长解绑老师
  getSchoolFileByLoginId: '/account/selectFilePager', // 获取学校上传附件,
  deleteSchoolFile: '/schoolFile/deleteData', // 删除文件
  downloadSchoolFile: '/schoolFile/downLoadBatch', // 下载文件
  uploadFile: '/user/uploadFile', // 上传文件
  addSchoolFile: '/schoolFile/addData', // 添加文件
  getAllNation: '/student/getAllNation', // 获取所有民族
  findClassesByLoginId: '/account/findClassesByLoginIdPager', // 根据当前登录用户获取班级
  findStudentBySchool: '/student/findStudentBySchool', // 根据学校查询学生列表
  getStudentInfoById: '/student/getStudentInfoById', // 根据学生id查询学生详情
  getAllAccountMenus: '/account/getAllMenus', // 获取所有权限
  getMenusByLoginId: '/account/getMenusByAccountId', // 根据登录获取权限
  setAccountMenus: '/account/setMenus', // 设置权限
  getAccountPager: '/account/getAccountPager', // 查询账号列表
  addAccount: '/account/addAccount', // 新增账号
  editAccount: '/account/editAccount', // 编辑账号
  setAccountState: '/account/setState', // 设置账号登录状态
  deleteAccount: '/account/deleteAccount', // 删除账号,
  searchSchoolForeword: '/school/searchSchoolForeword', // 根据id获得卷首语
  addSchoolForeword: '/school/addSchoolForeword', // 新增卷首语
  editSchoolForeword: '/school/editSchoolForeword', // 编辑卷首语
  getTeacherInfoByLoginId: '/teacher/getTeacherInfoByLoginId', // 根据用户ID获取教师详情
  getTeacherQualificationByLoginId: '/teacher/getTeacherQualificationByLoginId', // 根据登录用户ID获取教师资格证详情
  getTeacherHonorByLoginId: '/teacher/getTeacherHonorByLoginId', // 根据登录用户获取个人荣誉集合
  findTeacherPaperByLoginId: '/teacher/findTeacherPaperByLoginId', // 根据登录用户获取论文
  exportClasses: '/account/exportClasses', // 导出班级
  exportTeacher: '/account/exportTeacher', // 导出教职工
  exportStudentByAccountId: '/account/exportStudentByAccountId', // 导出学生
  downRespectExcel: '/user/downRespectExcel', // 下载教师导入模板
  importTeacher: '/account/importTeacher', // 批量导入教师
  findSemester: '/semester/findSemester', // 查询学期
  addSemester: '/semester/addSemester', // 新增学期
  updateSemester: '/semester/updateSemester', // 编辑学期
  getAllArticleType: '/pageArticle/getAllType', // 得到所有文章类型
  findPageArticleByType: '/pageArticle/findPageArticleByType' // 通过文章类型得到文章
}
